version:  '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
    command: make start
    volumes:
      - ./app/:/app
    ports:
      - 8080:8080

  caddy:
    image: caddy:2.4.5-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - $PWD:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
