version:  '3.9'

services:
  app:
    image: jeks0n/devops-for-programmers-project-lvl1:v1.0.3
    container_name: hexlet-app
    build:
      dockerfile: Dockerfile.production
      context: app
    command: npm test
    restart: unless-stopped
    stdin_open: true
    tty: true
