version:  '3.9'

services:
  db:
    container_name: hexlet-db
    image: postgres:13.2-alpine
    env_file: ./app/.env
    restart: unless-stopped
    volumes:
      - postgress_volume:/var/lib/postgresql/data

  app:
    image: jeks0n/devops-for-programmers-project-lvl1
    container_name: hexlet-app
    build:
      dockerfile: Dockerfile.production
      context: .
    command: npm test
    env_file: ./app/.env
    restart: unless-stopped
    tty: true

volumes:
  postgress_volume:
