version:  '3.8'

services:
  db:
    container_name: hexlet-db
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: jeks0n/devops-for-programmers-project-lvl1
    container_name: hexlet-app
    build:
      dockerfile: Dockerfile.production
      context: .
    command: npm test
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    restart: unless-stopped
    tty: true

volumes:
  pgdata:
