version:  '3.9'

services:
  db:
    container_name: hexlet-db
    image: postgres:13.2-alpine
    env_file: ./app/.env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: jeks0n/devops-for-programmers-project-lvl1
    container_name: hexlet-app
    build:
      dockerfile: Dockerfile.production
      context: .
    env_file: ./app/.env
    command: npm test
    restart: unless-stopped
    tty: true

volumes:
  pgdata:
